### ISSUE TITLE
variable color font not rendering in Chrome 106 beta

### ISSUE THREAD

**Issue by anthrotype** [simoncozens/parallax#1]
Hello!
I wanted to test this color font in Chrome 106 beta with the variable COLRv1 flag enabled, so I cloned the repo, made a venv, installed the requirements and run build-parallax.py script. This is the resulting font: [Parallax-VF.zip](https://github.com/simoncozens/parallax/files/9634807/Parallax-VF.zip)

I can see the COLR table has PaintVar* and a VarStore, there's an fvar with the axes definition, it looks valid and correct.
However, when I try to load the font using the following html file, I can only see it in black and white, no colors are displayed, no matter what I set for the XSEP and YSEP axes.

I only tested this on ChromeOS M106 beta.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Parallax</title>
  <style>
@font-face {
  font-family: "Parallax";
  src: url(Parallax-VF.ttf) format('truetype');
}
.Parallax {
  font-family: "Parallax";
  font-size: 4em;
  /* font-variation-settings: "XSEP" -40.8529, "YSEP" 32.0265; */
}
</style>
</head>

<body>
<pre>
  Intended to be run locally, such as with python -m http.server 8001
</pre>

<div class="Parallax">
 Parallax is cool!
</div>
</body>

</html>
```

**Comment by anthrotype** [comment]
I just tried on Chrome 105 (stable) on Linux, with the variable-colrv1 flag also enabled, and it doesn't work either.

**Comment by simoncozens** [comment]
I also see this problem! It works fine in FontGoggles, so I am not sure what's going on.

**Comment by anthrotype** [comment]
ok, I will ask @drott to take a look

**Comment by drott** [comment]
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/1021784/191996432-8ee56f74-6baf-45b9-b4b7-9c3b183abad1.png">

Works for me in 

Google Chrome | 108.0.5317.0 (Official Build) canary (arm64)
-- | --


Variable COLRv1 needs Canary and the flag enabled. Any earlier versions are not guaranteed to work well for variable COLRv1 fonts. Variable COLRv1 support in Chrome is likely going to be released in 108.

**Comment by anthrotype** [comment]
cool! thank you Dominik! 👍

**Comment by drott** [comment]
Not working for me in FF nightly, filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1792214

**Comment by simoncozens** [comment]
Man, it looks much worse on a white background than it does on a black one. Time to break out multiple palettes!

**Comment by jfkthame** [comment]
FTR, the failure in Firefox Nightly seems to be triggered by the font having COLRv1 variations (so an 'fvar' table is present) but no 'gvar' -- it looks like this confuses the Core Text APIs that Gecko relies on to get glyph outlines and advances, and as soon as any non-default variation values are passed, the glyphs (and advance widths) collapse.

As a workaround, adding an empty 'gvar' table to the font fixes it. I'm going to see if we can do something within Gecko to handle this.

**Comment by anthrotype** [comment]
interesting, thanks Jonathan. Maybe fonttools should add an empty gvar when building a VF with varaible COLR that has no variations in the glyph outlines themselves.

**Comment by anthrotype** [comment]
actually, fontTools.varLib (used by fontmake) already does add a `gvar` unconditionally when building a truetype-flavoured VF. Maybe this only applies for @simoncozens specific build setup, where he makes a static font and then he adds variable COLR and fvar as a post-processing step.

**Comment by drott** [comment]
Thanks for the quick analysis, @jfkthame. Commented on https://bugzilla.mozilla.org/show_bug.cgi?id=1792214#c4 - Chrome no longer requires gvar, and i suggest we phase out adding superfluous `gvar` "just in case". I suggest to insert gvar client side if needed before passing to CoreText.
